### ISSUE TITLE
Mipmaps for z-axis

### ISSUE THREAD

**Issue by CosmicElysium** [idia-astro/cpp_hdf5converter#51]
Currently mipmaps are downsampled and stored slice-by-slice for each x-y plane. We should also include additional mipmaps that downsample along the z-axis.

This will be useful for visual applications that simultaneously display multiple z-slices, such as incorporation of VR with Carta.

**Comment by CosmicElysium** [comment]
@confluence or @veggiesaurus , for the mipmaps that result from this, the z-downsampling would be independent of XY. So would we have something like:

DATA_XY_1_Z_2
DATA_XY_1_Z_4

DATA_XY_2_Z_1
DATA_XY_2_Z_2
DATA_XY_2_Z_4

DATA_XY_4_Z_1
DATA_XY_4_Z_2
DATA_XY_4_Z_4


Or maybe we remove the designation if downsampling does not occur (= 1)?
Such as 

DATA_Z_2
DATA_Z_4

DATA_XY_2
DATA_XY_2_Z_2
DATA_XY_2_Z_4

DATA_XY_4
DATA_XY_4_Z_2
DATA_XY_4_Z_4

**Comment by veggiesaurus** [comment]
Having the _1 as implicit rather than explicit would make it more readable and allow us to keep the same schema as before without resorting to aliases

**Comment by confluence** [comment]
I was thinking more about the naming scheme earlier, and I don't think it makes sense to separate the XY and the Z -- X and Y are two different dimensions (which we just happen to couple frequently because they're both spatial in our typical data and Z is not).

My suggestion would be to list all downsampled dimensions without separators, and then provide either a single number (if all dimensions are downsampled by the same factor) or as many numbers as there are dimensions, in order, separated by underscores. Dimensions that are not downsampled should be omitted (as is currently done with Z in the XY mipmaps).

This is consistent with the current schema, and also makes the dataset names easier to parse (otherwise a name starting with `DATA_XY_` could be all kinds of completely different things, even if we group the dimensions at the front but keep the underscores). This way if we split by underscore we unambiguously get 1) original dataset, 2) all downsampled dimensions, 3) 1 or N downsampling factors.

So your examples above would be:

DATA_Z_2
DATA_Z_4

DATA_XY_2
DATA_XYZ_2
DATA_XYZ_2_2_4

DATA_XY_4
DATA_XYZ_4_4_2
DATA_XYZ_4

I'm open to elegant suggestions for avoiding the repetition of the X and Y downsampling factors which don't rely on the meaning of the axes -- but I think this may be the only unambiguous way to specify them.

(If we used underscores to split the dimensions into groups which are coupled, we could have one factor per group, but I think having an unambiguous name prefix is more important than not writing the extra number.)

**Comment by confluence** [comment]
Unless we use a different separator within the factors and dimensions. So something like:

DATA_Z_2
DATA_Z_4

DATA_XY_2
DATA_XY.Z_2
DATA_XY.Z_2.4

DATA_XY_4
DATA_XY.Z_4.2
DATA_XY.Z_4

Do you think that's better or worse? This may be overly complicated.

**Comment by CosmicElysium** [comment]
> DATA_Z_2
DATA_Z_4

>DATA_XY_2
DATA_XYZ_2
DATA_XYZ_2_2_4

>DATA_XY_4
DATA_XYZ_4_4_2
DATA_XYZ_4

I think this one makes a lot of sense. This also leaves the scheme open to decouple X and Y if anybody ever had the need.
